### ISSUE TITLE
Authorization: inter-node authentication does not work for some nodes in cluster

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#530]

**Comment by ikopylov** [comment]
Cluster.yaml:
```
nodes:
- name: local_node_1
address: "10.5.7.195:20000"
disks:
- name: disk1
path: /opt/disk1
- name: disk2
path: /opt/disk2
- name: disk3
path: /opt/disk3
- name: disk4
path: /opt/disk4
- name: local_node_2
address: "10.5.7.241:20000"
disks:
- name: disk1
path: /opt/disk1
- name: disk2
path: /opt/disk2
- name: disk3
path: /opt/disk3
- name: disk4
path: /opt/disk4
- name: local_node_3
address: "10.5.7.217:20000"
disks:
- name: disk1
path: /opt/disk1
- name: disk2
path: /opt/disk2
- name: disk3
path: /opt/disk3
- name: disk4
path: /opt/disk4
- name: local_node_4
address: "10.5.7.212:20000"
disks:
- name: disk1
path: /opt/disk1
- name: disk2
path: /opt/disk2
- name: disk3
path: /opt/disk3
- name: disk4
path: /opt/disk4
vdisks:
- id: 0
replicas:
- node: local_node_1
disk: disk1
- node: local_node_2
disk: disk1
- id: 1
replicas:
- node: local_node_1
disk: disk2
- node: local_node_2
disk: disk2
- id: 2
replicas:
- node: local_node_1
disk: disk3
- node: local_node_2
disk: disk3
- id: 3
replicas:
- node: local_node_1
  disk: disk4
- node: local_node_2
  disk: disk4
racks: []
distribution_func: Mod
```
