### ISSUE TITLE
Reading file with cluster configuration

### ISSUE THREAD

**Issue by agend** [qoollo/bob#7]
File format:
```
vdisks:
   - id: 0
     replicas:
               - 127.0.0.1:4401:/opt/disk1
               - 10.0.0.1:4401:/opt/disk1
   - id: 1
   - id: 2
     replicas:
               - 127.0.0.1:4401:/opt/disk2
               - 10.0.0.1:4401:/opt/disk2
               - 10.0.0.2:4401:/opt/disk1
      
```

this will be need for this: https://github.com/qoollo/bob/blob/master/src/core/sprinkler.rs#L59
