### ISSUE TITLE
Loss of records in the test with aliens

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#806]
In test with aliens small number of records are not read at the end.
Test plan:
- 4 nodes, replication = 2
- Write 100k, then read that 100k
- Stop 1st node, write additional 100k, read this additional 100k
- Stop 2nd node, write additional 100k, read this additional 100k
- Stop 3rd node, write additional 100k, read this additional 100k
- Turn on all 3 stopped nodes and read all 400k records

Script:
```sh
bobp -b put -c 100000 -l 10240 -t 32 -h 10.5.7.212 && 
sleep 60 && 
bobp -b exist -c 100000 -l 10240 -t 32 -h 10.5.7.212 && 
ssh root@10.5.7.212 "systemctl stop bob" && 
sleep 60 && 
bobp -b put -c 100000 -f 100000 -l 10240 -t 32 -h 10.5.7.217 && 
sleep 60 && 
bobp -b exist -c 100000 -f 100000 -l 10240 -t 32 -h 10.5.7.217 && 
ssh root@10.5.7.217 "systemctl stop bob" && 
sleep 60 && 
bobp -b put -c 100000 -f 200000 -l 10240 -t 32 -h 10.5.7.241 && 
sleep 60 && 
bobp -b exist -c 100000 -f 200000 -l 10240 -t 32 -h 10.5.7.241 && 
ssh root@10.5.7.241 "systemctl stop bob" && 
sleep 60 && 
bobp -b put -c 100000 -f 300000 -l 10240 -t 32 -h 10.5.7.195 && 
sleep 60 && 
bobp -b exist -c 100000 -f 300000 -l 10240 -t 32 -h 10.5.7.195 && 
ssh root@10.5.7.212 "systemctl restart bob" && 
ssh root@10.5.7.217 "systemctl restart bob" && 
ssh root@10.5.7.241 "systemctl restart bob" && 
sleep 60 && 
bobp -b exist -c 400000 -l 10240 -h 10.5.7.195 -t 32
```

сluster.yaml:
```yaml
nodes:
  - name: local-node-1
    address: "10.5.7.195:20000"
    disks:
      - name: disk1
        path: /opt/disk1
  - name: local-node-2
    address: "10.5.7.241:20000"
    disks:
      - name: disk1
        path: /opt/disk1
  - name: local-node-3
    address: "10.5.7.217:20000"
    disks:
      - name: disk1
        path: /opt/disk1
  - name: local-node-4
    address: "10.5.7.212:20000"
    disks:
      - name: disk1
        path: /opt/disk1
vdisks:
  - id: 0
    replicas:
      - node: local-node-1
        disk: disk1
      - node: local-node-2
        disk: disk1
  - id: 1
    replicas:
      - node: local-node-3
        disk: disk1
      - node: local-node-4
        disk: disk1
  - id: 2
    replicas:
      - node: local-node-1
        disk: disk1
      - node: local-node-2
        disk: disk1
  - id: 3
    replicas:
      - node: local-node-3
        disk: disk1
      - node: local-node-4
        disk: disk1
racks: []
distribution_func: Mod
```

Records are lost in the range 200000-299999.
Operation timeout: 30s.

It is possible that the problem may be related to disconnect detection
