### ISSUE TITLE
`ccg`: Avoid a complete match of the list of vdisks on different physical disks of nodes

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#811]
Example of a bad cluster.yaml:
```yaml
nodes:
  - name: local-node-1
    address: "10.5.7.195:20000"
    disks:
      - name: disk1
        path: /opt/disk1
  - name: local-node-2
    address: "10.5.7.241:20000"
    disks:
      - name: disk1
        path: /opt/disk1
  - name: local-node-3
    address: "10.5.7.217:20000"
    disks:
      - name: disk1
        path: /opt/disk1
  - name: local-node-4
    address: "10.5.7.212:20000"
    disks:
      - name: disk1
        path: /opt/disk1
vdisks:
  - id: 0
    replicas:
      - node: local-node-1
        disk: disk1
      - node: local-node-2
        disk: disk1
  - id: 1
    replicas:
      - node: local-node-3
        disk: disk1
      - node: local-node-4
        disk: disk1
  - id: 2
    replicas:
      - node: local-node-1
        disk: disk1
      - node: local-node-2
        disk: disk1
  - id: 3
    replicas:
      - node: local-node-3
        disk: disk1
      - node: local-node-4
        disk: disk1
racks: []
distribution_func: Mod
```
Here ` local-node-1` and `local-node-2` are mirrors of each other. They contains `vdisk 0` and `vdisk 2`. The same is for `local-node-3` and `local-node-4`. If both nodes stops working, we lost access to 2 vdisks.

The following distribution is better:
```yaml
vdisks:
  - id: 0
    replicas:
      - node: local-node-1
        disk: disk1
      - node: local-node-2
        disk: disk1
  - id: 1
    replicas:
      - node: local-node-3
        disk: disk1
      - node: local-node-4
        disk: disk1
  - id: 2
    replicas:
      - node: local-node-1
        disk: disk1
      - node: local-node-3
        disk: disk1
  - id: 3
    replicas:
      - node: local-node-2
        disk: disk1
      - node: local-node-4
        disk: disk1
```
In this case if 2 nodes is turned off, then we lost only 1 vdisk
